# Generated by Django 4.2.7 on 2023-11-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=64, verbose_name='Bank name')),
                ('bank_founder_name', models.CharField(max_length=64, verbose_name="Bank's founder name")),
                ('bank_founder_surname', models.CharField(max_length=100, verbose_name="Bank's founder surname")),
                ('bank_founder_city', models.CharField(max_length=255, verbose_name='City where bank was started')),
                ('bank_found_date', models.DateTimeField(verbose_name='Date when bank was started')),
            ],
        ),
    ]
