# Generated by Django 4.2.7 on 2023-12-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bank_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
