# Generated by Django 4.2.7 on 2023-12-06 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_bank_bank_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bank_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Bank description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_founder_birthday',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Birthday of bank owner'),
            preserve_default=False,
        ),
    ]
