# Generated by Django 4.2.7 on 2023-12-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_bank_bank_description_bank_bank_founder_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='bank_founder_city',
            new_name='bank_city',
        ),
    ]
